[package]
name = "ifi-blog-rs"
version = "0.1.0"
authors = ["robinwilliam.hundt <robinwilliam.hundt@stud.uni-goettingen.de>"]
edition = "2018"

[dependencies]
rocksdb = "0.12.3"
telegram-bot = {git = "https://github.com/robinhundt/telegram-bot.git"}
byteorder = "1.3.2"
rss = { version = "1.8.0", features = ["from_url"] }
futures-preview = "0.3.0-alpha.18"
tokio = "0.2.0-alpha.5"
snafu = "0.5.0"
log = "0.4.8"
env_logger = "0.7.0"
